import type { Metadata } from "next";
import { DM_Sans, Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const Dm_San = DM_Sans({ 
  subsets: ["latin"],
  weight:['100','200','300','400','500','600','700','800','900'],
  variable:'--font-dmsans'
  });

const Poppins_ = Poppins({ 
  subsets: ["latin"],
  weight:['100','200','300','400','500','600','700','800','900'],
  variable:'--font-poppins'
  });

export const metadata: Metadata = {
  title: "scope of services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
